### ISSUE TITLE
file path json wrong

### ISSUE THREAD

**Issue by somatonic** [USSliberty/italian-processwire#2]
I tried to load the italian translations (pw2.7.3)

Now most files don't work and when clicking edit it shows me that the file doesn't exists.

All those path are different than what I have with other language translation packs.

"file": "wire\core\InputfieldWrapper.php",

should be

"file": "wire\/core\/InputfieldWrapper.php",

**Comment by USSliberty** [comment]
Hi Soma,

I suspect that is because those files are from a processwire installation on windows.

@mauricius can you confirm that have you translated Processwire on Windows?

**Comment by mauricius** [comment]
Yeah @USSliberty is right! Unfortunately I switched on a Mac just a few months ago. However I just pushed #3 to fix the issue.

Sorry for the inconvenience @somatonic

**Comment by USSliberty** [comment]
Great @mauricius ! 
However Processwire does support Windows, maybe it worth to open an issue here: https://github.com/ryancramerdesign/ProcessWire/issues
